from __future__ import annotations

import json
import os
import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .frontend_scaffold import (
    OPENAPI_GENERATOR_NAME,
    OPENAPI_GENERATOR_VERSION,
    FrontendScaffoldError,
    openapi_typescript_fetch_command,
    render_package_lock,
    resolve_api_base_url,
    write_react_scaffold,
)

CommandRunner = Callable[[str, list[str], Path], object]


def repair_typescript_fetch_export_collisions(generated_client: Path) -> list[str]:
    """Rename inline operation parameter types that collide with model exports.

    ``typescript-fetch`` emits an inline interface in an API module for some
    path-parameter operations.  If that interface has the same name as a
    request model, the generated root index re-exports both and TypeScript
    fails with TS2308.  Keep the generated API behaviour intact while making
    the colliding API-local type name unique.
    """
    models_root = generated_client / "src" / "models"
    apis_root = generated_client / "src" / "apis"
    if not models_root.is_dir() or not apis_root.is_dir():
        return []
    model_names = {
        path.stem
        for path in models_root.glob("*.ts")
        if path.stem and path.stem != "index"
    }
    repaired: list[str] = []
    for api_path in apis_root.glob("*.ts"):
        if api_path.name == "index.ts":
            continue
        source = api_path.read_text(encoding="utf-8")
        collisions = sorted(
            name
            for name in model_names
            if re.search(rf"\bexport interface {re.escape(name)}\b", source)
        )
        for name in collisions:
            source = re.sub(
                rf"(?<!/)\b{re.escape(name)}\b",
                f"{name}Params",
                source,
            )
            repaired.append(f"{api_path.name}: {name} -> {name}Params")
        if collisions:
            api_path.write_text(source, encoding="utf-8")
    return repaired


@dataclass(frozen=True)
class FrontendGenerationResult:
    api_base_url: str
    generator: str
    generator_version: str

    def artifact_metadata(self, application_name: str) -> dict[str, str]:
        return {
            "generator": f"openapi-generator/{self.generator}@{self.generator_version}",
            "stage": "SCAFFOLD",
            "application_name": application_name,
            "api_base_url": self.api_base_url,
        }

    def tool_metadata(self) -> dict[str, str]:
        return {
            "generator": self.generator,
            "version": f"openapi-generator-cli/v{self.generator_version}",
        }


def generate_frontend_project(
    *,
    workspace_root: Path,
    openapi_path: Path,
    frontend_root: Path,
    api_spec: dict[str, Any],
    application_name: str,
    api_base_url: str | None,
    run_command: CommandRunner,
) -> FrontendGenerationResult:
    """Generate the client, deterministic React shell, and npm dependency lock."""
    effective_api_base_url = resolve_api_base_url(api_spec, api_base_url)
    generated_client = frontend_root / "src" / "generated"
    run_command(
        "openapi-generator-typescript-fetch",
        openapi_typescript_fetch_command(
            workspace_root, openapi_path, generated_client
        ),
        workspace_root,
    )
    # typescript-fetch exposes its barrel at ``src/generated/src/index.ts``.
    # Keep a root compatibility barrel as well so pages generated by older
    # prompts importing ``../generated`` still resolve the same client.
    generated_source_index = generated_client / "src" / "index.ts"
    generated_root_index = generated_client / "index.ts"
    if generated_source_index.is_file() and not generated_root_index.exists():
        generated_root_index.write_text("export * from './src';\n", encoding="utf-8")
    repair_typescript_fetch_export_collisions(generated_client)
    scaffold = write_react_scaffold(
        frontend_root,
        api_spec,
        application_name=application_name,
        api_base_url=effective_api_base_url,
    )
    rendered_lock = render_package_lock(scaffold["package.json"])
    if rendered_lock is not None:
        (frontend_root / "package-lock.json").write_text(
            rendered_lock, encoding="utf-8"
        )
    else:
        npm = "npm.cmd" if os.name == "nt" else "npm"
        run_command(
            "npm-package-lock",
            [
                npm,
                "install",
                "--package-lock-only",
                "--ignore-scripts",
                "--no-audit",
                "--no-fund",
            ],
            frontend_root,
        )
    if not (frontend_root / "package-lock.json").is_file():
        raise FrontendScaffoldError(
            "npm package-lock generation completed without package-lock.json"
        )
    return FrontendGenerationResult(
        api_base_url=effective_api_base_url,
        generator=OPENAPI_GENERATOR_NAME,
        generator_version=OPENAPI_GENERATOR_VERSION,
    )


def write_openapi_input(path: Path, api_spec: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(api_spec, ensure_ascii=False, indent=2), encoding="utf-8"
    )
