"""Audited provider resource labels and Terraform primitive types."""

from __future__ import annotations

from typing import Any

_PROVIDER_MODELS: dict[str, dict[str, Any]] = {
    "aws": {
        "resources": {
            "compute-instance": ("EC2 Instance", "compute"),
            "compute-group": ("EC2 Auto Scaling Group", "compute"),
            "compute-template": ("EC2 Launch Template", "compute"),
            "boot-image": ("Amazon Machine Image (AMI)", "compute"),
            "app-registry": ("Amazon ECR Repository", "config"),
            "registry-pull-identity": ("IAM Role / VM Registry Pull", "security"),
            "registry-pull-policy": (
                "AmazonEC2ContainerRegistryReadOnly Policy",
                "security",
            ),
            "registry-pull-binding": ("IAM Role Policy Attachment", "security"),
            "registry-instance-profile": ("IAM Instance Profile", "security"),
            "secret-ref": ("Existing AWS Secret", "config"),
            "secret-access-binding": ("IAM Role Policy / Secret Read", "security"),
            "state-secret-identity": ("IAM Role / State Secret Read", "security"),
            "state-secret-access-binding": (
                "IAM Role Policy / State Secret Read",
                "security",
            ),
            "state-secret-instance-profile": (
                "IAM Instance Profile / State VM",
                "security",
            ),
            "load-balancer": ("Network Load Balancer", "network"),
            "listener": ("Network Load Balancer Listener", "network"),
            "backend-group": ("Target Group", "network"),
            "health-check": ("Target Group / Health Check", "network"),
            "network": ("VPC", "network"),
            "subnet": ("Application Subnet", "network"),
            "state-subnet": ("State Subnet", "network"),
            "ingress-subnet": ("Ingress Subnet", "network"),
            "security-group": ("Security Group / Application", "network"),
            "load-balancer-security-group": ("Security Group / Load Balancer", "network"),
            "application-ingress-rule": (
                "Terraform: aws_vpc_security_group_ingress_rule / from Load Balancer",
                "network",
            ),
            "internet-gateway": ("Internet Gateway", "network"),
            "ingress-route-table": ("Route Table / ingress", "network"),
            "ingress-default-route": ("Terraform: aws_route / Internet Gateway", "network"),
            "ingress-route-association": (
                "Terraform: aws_route_table_association / ingress",
                "network",
            ),
            "application-route-table": ("Route Table / application", "network"),
            "application-default-route": ("Terraform: aws_route / NAT Gateway", "network"),
            "application-route-association": (
                "Terraform: aws_route_table_association / application",
                "network",
            ),
            "nat-public-ip": ("Elastic IP / NAT Gateway", "network"),
            "nat-gateway": ("NAT Gateway", "network"),
            "public-ip": ("Elastic IP", "network"),
            "disk": ("EBS Volume", "storage"),
            "disk-attachment": ("Terraform: aws_volume_attachment", "storage"),
        },
        "componentIds": {
            "nlb": "load-balancer",
            "listener": "listener",
            "target-group": "backend-group",
            "target-group-health": "health-check",
        },
        "officialAliases": {},
        "embeddedOwners": {
            "health-check": "backend-group",
        },
        "groupTopologyEdges": (
            ("compute-group", "compute-template", "uses"),
            ("compute-group", "subnet", "places instances in"),
            ("compute-template", "security-group", "uses"),
            ("compute-group", "backend-group", "registers instances with"),
            ("subnet", "network", "belongs to"),
            ("security-group", "network", "belongs to"),
        ),
        "standaloneEdges": (
            ("compute-instance", "subnet", "is placed in"),
            ("compute-instance", "security-group", "attaches"),
            ("subnet", "network", "belongs to"),
            ("security-group", "network", "belongs to"),
        ),
        "standaloneCapabilityEdges": (),
        "capabilityEdges": (
            ("listener", "load-balancer", "belongs to"),
            ("listener", "backend-group", "forwards to"),
            ("backend-group", "health-check", "evaluates targets with"),
        ),
    },
    "azure": {
        "resources": {
            "compute-instance": ("Linux Virtual Machine", "compute"),
            "compute-group": ("Virtual Machine Scale Set", "compute"),
            "resource-group": ("Resource Group", "config"),
            "boot-image": ("Virtual Machine Image", "compute"),
            "app-registry": ("Container Registry", "config"),
            "registry-pull-identity": ("User-assigned Managed Identity", "security"),
            "registry-pull-binding": ("AcrPull Role Assignment", "security"),
            "secret-ref": ("Existing Key Vault Secret", "config"),
            "secret-access-binding": ("Key Vault Secrets User Role Assignment", "security"),
            "state-secret-identity": (
                "User-assigned Managed Identity / State VM",
                "security",
            ),
            "state-secret-access-binding": (
                "Key Vault Secrets User Role Assignment / State VM",
                "security",
            ),
            "load-balancer": ("Load Balancer", "network"),
            "frontend-ip-config": (
                "Load Balancer / Frontend IP Configuration",
                "network",
            ),
            "backend-group": ("Backend Address Pool", "network"),
            "health-check": ("Probe", "network"),
            "routing-rule": ("Load Balancing Rule", "network"),
            "backend-membership": (
                "Network Interface Backend Address Pool Association",
                "network",
            ),
            "network": ("Virtual Network", "network"),
            "subnet": ("Application Subnet", "network"),
            "network-interface": ("Network Interface", "network"),
            "security-group": ("Network Security Group", "network"),
            "security-group-association": ("NIC Security Group Association", "network"),
            "public-ip": ("Public IP", "network"),
            "nat-public-ip": ("Public IP / NAT Gateway", "network"),
            "nat-gateway": ("NAT Gateway", "network"),
            "nat-association": (
                "Terraform: azurerm_subnet_nat_gateway_association",
                "network",
            ),
            "nat-public-ip-association": (
                "Terraform: azurerm_nat_gateway_public_ip_association",
                "network",
            ),
            "disk": ("Managed Disk", "storage"),
            "disk-attachment": (
                "Terraform: azurerm_virtual_machine_data_disk_attachment",
                "storage",
            ),
        },
        "componentIds": {
            "load-balancer": "load-balancer",
            "frontend-ip-config": "frontend-ip-config",
            "backend-pool": "backend-group",
            "probe": "health-check",
            "load-balancing-rule": "routing-rule",
            "backend-membership": "backend-membership",
        },
        "officialAliases": {},
        "embeddedOwners": {
            "frontend-ip-config": "load-balancer",
        },
        "groupTopologyEdges": (
            ("compute-group", "network-interface", "uses"),
            ("network-interface", "subnet", "is attached to"),
            ("network-interface", "security-group", "uses"),
            ("compute-group", "backend-membership", "joins"),
            ("subnet", "network", "belongs to"),
        ),
        "standaloneEdges": (
            ("compute-instance", "network-interface", "uses"),
            ("network-interface", "subnet", "is attached to"),
            ("security-group-association", "network-interface", "binds"),
            ("security-group-association", "security-group", "binds"),
            ("subnet", "network", "belongs to"),
        ),
        "standaloneCapabilityEdges": (
            ("network-interface", "backend-membership", "joins through"),
        ),
        "capabilityEdges": (
            ("frontend-ip-config", "load-balancer", "belongs to"),
            ("backend-group", "load-balancer", "belongs to"),
            ("health-check", "load-balancer", "belongs to"),
            ("routing-rule", "load-balancer", "belongs to"),
            ("routing-rule", "frontend-ip-config", "uses"),
            ("routing-rule", "backend-group", "routes to"),
            ("routing-rule", "health-check", "uses"),
            ("backend-membership", "backend-group", "registers instances with"),
        ),
    },
    "gcp": {
        "resources": {
            "compute-instance": ("Compute Engine VM", "compute"),
            "compute-group": ("Regional Managed Instance Group", "compute"),
            "backend-group": ("Unmanaged Instance Group", "compute"),
            "compute-template": ("Instance Template", "compute"),
            "boot-image": ("Compute Engine OS Image", "compute"),
            "app-registry": ("Artifact Registry Repository", "config"),
            "registry-pull-identity": ("Service Account / VM Registry Pull", "security"),
            "registry-pull-binding": (
                "Artifact Registry Reader IAM Member",
                "security",
            ),
            "secret-ref": ("Existing Secret Manager Secret", "config"),
            "secret-access-binding": ("Secret Manager Secret Accessor IAM Member", "security"),
            "state-secret-identity": (
                "Service Account / State Secret Read",
                "security",
            ),
            "state-secret-access-binding": (
                "Secret Manager Secret Accessor IAM Member / State VM",
                "security",
            ),
            "forwarding-rule": ("Forwarding Rule", "network"),
            "backend-service": ("Region Backend Service", "network"),
            "health-check": ("Region Health Check", "network"),
            "network": ("VPC Network", "network"),
            "subnet": ("Subnetwork", "network"),
            "cloud-router": ("Cloud Router", "network"),
            "cloud-nat": ("Cloud NAT", "network"),
            "network-interface": ("Compute resource / network_interface", "network"),
            "firewall": ("Firewall Rule", "network"),
            "public-ip": ("External IP Address", "network"),
            "disk": ("Persistent Disk", "storage"),
            "disk-attachment": ("Terraform: google_compute_attached_disk", "storage"),
        },
        "componentIds": {
            "forwarding-rule": "forwarding-rule",
            "backend-service": "backend-service",
            "instance-group": "backend-group",
            "health-check": "health-check",
        },
        "officialAliases": {"backend-group": "backend-group"},
        "embeddedOwners": {
            "network-interface": "compute-instance",
        },
        "groupTopologyEdges": (
            ("compute-group", "compute-template", "creates instances from"),
            ("compute-template", "network-interface", "uses"),
            ("network-interface", "subnet", "is attached to"),
            ("compute-group", "firewall", "is reached through"),
            ("subnet", "network", "belongs to"),
            ("firewall", "network", "belongs to"),
        ),
        "standaloneEdges": (
            ("compute-instance", "network-interface", "uses"),
            ("network-interface", "subnet", "is attached to"),
            ("subnet", "network", "belongs to"),
            ("firewall", "network", "belongs to"),
            ("firewall", "compute-instance", "allows traffic to"),
        ),
        "standaloneCapabilityEdges": (("backend-group", "compute-instance", "contains instance"),),
        "capabilityEdges": (
            ("forwarding-rule", "backend-service", "forwards to"),
            ("backend-service", "backend-group", "uses backend"),
            ("backend-service", "health-check", "checks with"),
        ),
    },
}


def _managed_l4_evidence(provider: str, enabled: bool) -> dict[str, Any]:
    """현재 선택한 관리형 L4 진입 경로에서 실제 관찰한 범위만 보고한다."""

    if not enabled:
        return {"status": "notApplicable", "evidenceRefs": []}

    selected_ingress = {
        "aws": "Network Load Balancer",
        "azure": "Load Balancer",
        "gcp": "Regional External Passthrough Network Load Balancer",
    }[provider]
    evidence_refs = {
        "aws": ["evaluation/dependency_audit/aws-managed-l4-ingress-result-20260817.json"],
        "azure": ["evaluation/dependency_audit/azure-managed-l4-ingress-result-20260817.json"],
        "gcp": ["evaluation/dependency_audit/gcp-managed-l4-ingress-result-20260817.json"],
    }[provider]
    return {
        "status": "observed",
        "evidenceRefs": evidence_refs,
        "selectedIngress": selected_ingress,
        "observed": [
            "L4 forwarding",
            "HTTP health checks",
            "two backend reachability",
            "backend process fault exclusion and operator-triggered restoration",
            "run-owned cleanup with zero residual resources",
        ],
        "notMeasured": [
            "availability SLA",
            "performance",
            "managed VM replacement",
        ],
    }


_OFFICIAL_ALIASES = {
    "load-balancer": "load-balancer",
    "backend-group": "backend-group",
    "virtual-network": "network",
    "network-interface": "network-interface",
    "security-group": "security-group",
}


_TERRAFORM_TYPES: dict[str, dict[str, tuple[str, ...]]] = {
    "aws": {
        "compute-instance": ("aws_instance",),
        "compute-group": ("aws_autoscaling_group",),
        "compute-template": ("aws_launch_template",),
        "app-registry": ("aws_ecr_repository",),
        "registry-pull-identity": ("aws_iam_role",),
        "registry-pull-binding": ("aws_iam_role_policy_attachment",),
        "registry-instance-profile": ("aws_iam_instance_profile",),
        "secret-access-binding": ("aws_iam_role_policy",),
        "state-secret-identity": ("aws_iam_role",),
        "state-secret-access-binding": ("aws_iam_role_policy",),
        "state-secret-instance-profile": ("aws_iam_instance_profile",),
        "load-balancer": ("aws_lb",),
        "listener": ("aws_lb_listener",),
        "backend-group": ("aws_lb_target_group",),
        "network": ("aws_vpc",),
        "subnet": ("aws_subnet",),
        "state-subnet": ("aws_subnet",),
        "ingress-subnet": ("aws_subnet",),
        "security-group": ("aws_security_group",),
        "load-balancer-security-group": ("aws_security_group",),
        "application-ingress-rule": ("aws_vpc_security_group_ingress_rule",),
        "internet-gateway": ("aws_internet_gateway",),
        "ingress-route-table": ("aws_route_table",),
        "ingress-default-route": ("aws_route",),
        "ingress-route-association": ("aws_route_table_association",),
        "application-route-table": ("aws_route_table",),
        "application-default-route": ("aws_route",),
        "application-route-association": ("aws_route_table_association",),
        "nat-public-ip": ("aws_eip",),
        "nat-gateway": ("aws_nat_gateway",),
        "public-ip": ("aws_eip",),
        "disk": ("aws_ebs_volume",),
        "disk-attachment": ("aws_volume_attachment",),
    },
    "azure": {
        "compute-instance": ("azurerm_linux_virtual_machine",),
        "compute-group": ("azurerm_linux_virtual_machine_scale_set",),
        "resource-group": ("azurerm_resource_group",),
        "app-registry": ("azurerm_container_registry",),
        "registry-pull-identity": ("azurerm_user_assigned_identity",),
        "registry-pull-binding": ("azurerm_role_assignment",),
        "secret-access-binding": ("azurerm_role_assignment",),
        "state-secret-identity": ("azurerm_user_assigned_identity",),
        "state-secret-access-binding": ("azurerm_role_assignment",),
        "load-balancer": ("azurerm_lb",),
        "backend-group": ("azurerm_lb_backend_address_pool",),
        "health-check": ("azurerm_lb_probe",),
        "routing-rule": ("azurerm_lb_rule",),
        "network": ("azurerm_virtual_network",),
        "subnet": ("azurerm_subnet",),
        "network-interface": ("azurerm_network_interface",),
        "security-group": ("azurerm_network_security_group",),
        "security-group-association": ("azurerm_network_interface_security_group_association",),
        "backend-membership": ("azurerm_network_interface_backend_address_pool_association",),
        "public-ip": ("azurerm_public_ip",),
        "nat-public-ip": ("azurerm_public_ip",),
        "nat-gateway": ("azurerm_nat_gateway",),
        "nat-association": ("azurerm_subnet_nat_gateway_association",),
        "nat-public-ip-association": ("azurerm_nat_gateway_public_ip_association",),
        "disk": ("azurerm_managed_disk",),
        "disk-attachment": ("azurerm_virtual_machine_data_disk_attachment",),
    },
    "gcp": {
        "compute-instance": ("google_compute_instance",),
        "compute-group": ("google_compute_region_instance_group_manager",),
        "backend-group": ("google_compute_instance_group",),
        "compute-template": ("google_compute_instance_template",),
        "app-registry": ("google_artifact_registry_repository",),
        "registry-pull-identity": ("google_service_account",),
        "registry-pull-binding": ("google_artifact_registry_repository_iam_member",),
        "secret-access-binding": ("google_secret_manager_secret_iam_member",),
        "state-secret-identity": ("google_service_account",),
        "state-secret-access-binding": ("google_secret_manager_secret_iam_member",),
        "forwarding-rule": ("google_compute_forwarding_rule",),
        "backend-service": ("google_compute_region_backend_service",),
        "health-check": ("google_compute_region_health_check",),
        "network": ("google_compute_network",),
        "subnet": ("google_compute_subnetwork",),
        "cloud-router": ("google_compute_router",),
        "cloud-nat": ("google_compute_router_nat",),
        "firewall": ("google_compute_firewall",),
        "public-ip": ("google_compute_address",),
        "disk": ("google_compute_disk",),
        "disk-attachment": ("google_compute_attached_disk",),
    },
}
